import Footer from "./components/footer";
import Navbar from "./components/navbar";
import TopNavbar from "./components/top-nav";
import "./global.css";

export const metadata = {
  title: "Welcome to web",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <TopNavbar />
          <Navbar />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
